-- MySQL Script generated by MySQL Workbench
-- Sat Sep  1 14:53:44 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema oauth
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `oauth` ;

-- -----------------------------------------------------
-- Schema oauth
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `oauth` DEFAULT CHARACTER SET utf8 ;
USE `oauth` ;

-- -----------------------------------------------------
-- Table `oauth`.`clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oauth`.`clients` ;

CREATE TABLE IF NOT EXISTS `oauth`.`clients` (
  `cli_id` INT NOT NULL AUTO_INCREMENT,
  `cli_client_identification` VARCHAR(80) NOT NULL,
  `cli_client_secret` VARCHAR(255) NOT NULL,
  `cli_client_name` VARCHAR(80) NOT NULL,
  `cli_grant_type` VARCHAR(20) NOT NULL,
  `cli_client_type` VARCHAR(15) NOT NULL,
  `cli_registration_date` DATETIME NOT NULL,
  UNIQUE INDEX `cli_name_UNIQUE` (`cli_client_name` ASC),
  PRIMARY KEY (`cli_id`),
  UNIQUE INDEX `cli_client_id_UNIQUE` (`cli_client_identification` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oauth`.`clients_scopes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oauth`.`clients_scopes` ;

CREATE TABLE IF NOT EXISTS `oauth`.`clients_scopes` (
  `sco_id` INT NOT NULL AUTO_INCREMENT,
  `sco_service` VARCHAR(30) NOT NULL,
  `sco_cli_id` INT NOT NULL,
  PRIMARY KEY (`sco_id`, `sco_cli_id`),
  INDEX `fk_scopes_clients_idx` (`sco_cli_id` ASC),
  CONSTRAINT `fk_scopes_clients`
    FOREIGN KEY (`sco_cli_id`)
    REFERENCES `oauth`.`clients` (`cli_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oauth`.`redirect_uri`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oauth`.`redirect_uri` ;

CREATE TABLE IF NOT EXISTS `oauth`.`redirect_uri` (
  `red_id` INT NOT NULL AUTO_INCREMENT,
  `red_url` VARCHAR(4000) NOT NULL,
  `red_cli_id` INT NOT NULL,
  PRIMARY KEY (`red_id`, `red_cli_id`),
  INDEX `fk_redirect_uri_clients1_idx` (`red_cli_id` ASC),
  CONSTRAINT `fk_redirect_uri_clients1`
    FOREIGN KEY (`red_cli_id`)
    REFERENCES `oauth`.`clients` (`cli_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
