sudo: required

language: php

services:
  - docker

php:
  - 7.2
  - nightly

before_script:
  - make travis
  - sleep 30

script:
  make travistest

after_success:
  - if [[ $TRAVIS_PHP_VERSION != "hhvm" ]]; then bash <(curl -s https://codecov.io/bash); fi

after_script:
  - docker-compose down