version: '3'
services:
  httpd:
    build:
      context: .
      args:
        - CA_COUNTRY=${CA_COUNTRY}
        - CA_STATE=${CA_STATE}
        - CA_LOCALITY=${CA_LOCALITY}
        - CA_ORGANIZATION=${CA_ORGANIZATION}
        - CA_ORGANIZATIONUNIT=${CA_ORGANIZATIONUNIT}
        - CA_COMMON=${VIRTUAL_HOST}
    container_name: httpd
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./src:/var/www/html
      - ./logs/apache2:/var/log/apache2
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
    networks:
      - backend
  mysql:
    image: mysql:5.7.22
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./db/mysql:/var/lib/mysql
    networks:
      - backend
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
    networks:
      - backend
  memcached:
    image: bitnami/memcached:latest
    container_name: memcached
    ports:
      - 11211:11211
    networks:
      - backend
networks:
  backend:
    driver: bridge
