version: '3'
networks:
  app-tier:
    driver: bridge
services:
  httpd:
    build: .
    container_name: httpd
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./src:/var/www/html
      - ./logs/apache2:/var/log/apache2
