<?php
/**
 * Created by PhpStorm.
 * User: thor
 * Date: 8/29/18
 * Time: 11:37 PM
 */

namespace Oauth\Services\Storage;

use Oauth\Services\AudienceInterface;
use Oauth\Services\Clients\ClientInterface;

interface ClientStorageInterface
{

    /**
     * Fetch a full representation of a client
     * @param string $clientId
     * @return ClientInterface|AudienceInterface
     */
    public function fetch(string $clientId);

    /**
     * @param $client
     */
    public function create($client) : void;

    /**
     * @param string $clientId
     */
    public function delete(string $clientId) : void;

    /**
     * Update all no-autogenerated client field (aka client_identification, client_secret, registration_date)
     * @param $client
     */
    public function update($client) : void;

    /**
     * @param string $currentClientId
     * @param string $newClientId
     * @return ClientInterface
     */
    public function updateIdentification(string $currentClientId, string $newClientId) : ClientInterface;

    /**
     * @param string $clientId
     * @param string $newSecret
     * @return ClientInterface
     */
    public function updateSecret(string $clientId, string $newSecret) : ClientInterface;
}